#pragma once
//This file includes all important headers so when the client imports something, they just have to include "FSY.h"

#include "FSY/Application/Application.h"
#include "FSY/Application/EntryPoint.h"
#include "FSY/Scene/Scene.h"
#include "FSY/Maths/Maths.h"
#include "FSY/Application/FSY_Time.h"
#include "FSY/Editor/SceneCameraController.h"
#include "FSY/Rendering/Camera.h"
#include "FSY/Editor/Console.h"
#include "FSY/Editor/EditorUI.h"
#include "FSY/Application/Settings.h"
#include "FSY/Maths/PerlinNoise.h"
#include "FSY/Rendering/MeshRenderer.h"